name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update APT
      run: sudo apt-get -y update
    - name: Install Dependencies
      run: sudo apt-get -y install mold libx11-dev libasound2-dev libudev-dev
    - uses: actions/checkout@v3

    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2

    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.7
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
